### PR TITLE
BUG: Change spelling

### PR DESCRIPTION
**Pull request by CJ-Wright**
I assume that the container in question is a dewar (made for cryo samples).

### CODE REVIEW

**Comment by klauer** [comment]
Good catch 😄

**Comment by arkilic** [comment]
Only one spelling bug? English is my secondary language, I am sure there is a lot more of these 🌵

**Comment by tacaswell** [comment]
:cactus: ?

Also, can we wrap text to 80char like code?  It makes the diffs way easier to read.

**Comment by arkilic** [comment]
Cactus was the closest thing to [this](http://www.cheneyag.org/newsite/images/whatever_hand_gesture_yard_sign.jpg)

Noted. I will do it once @hhslepicka and I have more to add next week. Any comments on the actual content of the docs?

**Pull request merged**
