### PR TITLE
FIX: Amostra wasn't allowing update on time field for all collections…

### PR DESCRIPTION
**Pull request by hhslepicka**
… and also not allowing name updates for Containers.

This PR fixes: #34 and #35 .

Attn. @arkilic

### CODE REVIEW

**Comment by hhslepicka** [comment]
The time will reflect like a file... last modified date.

**Comment by danielballan** [comment]
Catch me up: last I knew we weren't supporting any updates anywhere because of @arkillic's concerns about MongoDB's lack of atomicity. But amostra seems to support at least some updates. Fine by me, but I'd like to know what the current thinking is. What can be updated and why?

**Comment by danielballan** [comment]
Oops sorry for the misspelling, Arman.

**Comment by hhslepicka** [comment]
Amostra data has the need to be updated mainly because of typos that can happen and other situations such as the need to edit the contents of a container.
As the information taken care by amostra does not represent a large volume and it will very unlikely reach race conditions the updates are allowed here.

**Comment by arkilic** [comment]
@danielballan Now we have a server layer that ensures we don't have atomicity related issues.
Update support was one of the main reasons why we wanted to store sample information outside the mds header.

**Pull request merged**
