### PR TITLE
Fix max recursion

### PR DESCRIPTION
**Pull request by ke-zhang-rd**
This PR try to solve #51 and https://github.com/NSLS-II/amostra/pull/44#issuecomment-529455901.

Main difference comparing to #44 is addressing fix recursion.

### CODE REVIEW

**Comment by danielballan** [comment]
Why a new PR instead of adding commits to #44? It would be nice to keep the discussion in one place if possible.

**Comment by ke-zhang-rd** [comment]
> Why a new PR instead of adding commits to #44? It would be nice to keep the discussion in one place if possible.

Actually, what I want to do is remove test part of this PR and merge this first. Then proceed the other one, what do you think?

**Comment by danielballan** [comment]
Do you mean first fix the recursion issue in this PR and then add the hypothesis-related code in #44?

**Comment by ke-zhang-rd** [comment]
> Do you mean first fix the recursion issue in this PR and then add the hypothesis-related code in #44?

Yes. However now #44 has both bug fixed and hypothesis test and ready to be reviewed.

**Comment by ke-zhang-rd** [comment]
This is duplicated work which has been included in #44 . So, close it here.

**Pull request closed without merging**
